USE 12kchess;

CREATE TABLE USER(
ID VARCHAR(100) PRIMARY KEY,
PW VARCHAR(100) NOT NULL,
NAME VARCHAR(200) NOT NULL,
BIRTH DATE NOT NULL,
TELL VARCHAR(15) NOT NULL,
AUTHORITY VARCHAR(2) NOT NULL
);

ALTER TABLE USER ADD CONSTRAINT CK_ID CHECK (LENGTH(ID) > 3);
ALTER TABLE USER ADD CONSTRAINT CK_PW CHECK (LENGTH(PW) > 3);


#INSERT INTO user VALUES('4','1','US1',NOW(),'0-0-0','A');
INSERT INTO user VALUES('user1','1111','US3',NOW(),'0-0-0','C');
INSERT INTO user VALUES('user1','1111','US2',NOW(),'0-0-0','C');
INSERT INTO user VALUES('user1','1111','US3',NOW(),'0-0-0','C');
INSERT INTO user VALUES('user1','1111','US3',NOW(),'0-0-0','C');
INSERT INTO user VALUES('user1','1111','US3',NOW(),'0-0-0','C');



create table Notation(
	Nkey VARCHAR(100) PRIMARY KEY,
	id VARCHAR(100) NOT NULL,
	notation VARCHAR(5000) NOT NULL,
	title VARCHAR(500) DEFAULT 'no title',
	foreign key (id) references user(id) ON DELETE CASCADE
);




CREATE TABLE NOTATION_QNA(
NQID VARCHAR(100) PRIMARY KEY,
CONTENT TEXT(20000),
IMG VARCHAR(300) NOT NULL,
SUB VARCHAR(300) NOT NULL,
MYCOLOR CHAR(1) NOT NULL,
NKEY VARCHAR(100) NOT NULL,
ID VARCHAR(100) NOT NULL,
FOREIGN KEY (NKEY) REFERENCES notation(NKEY),
FOREIGN KEY (ID) REFERENCES USER(ID)
);
ALTER TABLE NOTATION_QNA ADD CONSTRAINT CK_MYCOLOR CHECK (MYCOLOR IN ('G','R')); #G 초록,R빨강

#INSERT INTO NOTATION_QNA VALUES('4','1','US1','DFSDF','G','1','DFD');


CREATE TABLE RANKING(
RKEY VARCHAR(100) PRIMARY KEY,
ID VARCHAR(100) NOT NULL,
SCORE INT NOT NULL,
SIGNDATE DATETIME NOT NULL,
BEFOREDATE DATETIME NOT NULL,
FOREIGN KEY (ID) REFERENCES USER(ID)
);

CREATE TABLE GAMESCHEDULE(
GCKEY VARCHAR(100) PRIMARY KEY,
PETITIONER VARCHAR(100) NOT NULL,
RESPONDENT VARCHAR(100) NOT NULL,
RESULT CHAR(1) NOT NULL,
REFEREE VARCHAR(100) NOT NULL,
DATE DATETIME NOT NULL,
Nkey VARCHAR(100) NOT NULL,
FOREIGN KEY (PETITIONER) REFERENCES USER(ID),
FOREIGN KEY (RESPONDENT) REFERENCES USER(ID),
FOREIGN KEY (REFEREE) REFERENCES USER(ID),
FOREIGN KEY (Nkey) REFERENCES Notation(Nkey)
);
ALTER TABLE GAMESCHEDULE ADD CONSTRAINT CK_RESULT CHECK (RESULT IN ('P','R','D')); #P가이김,R이이김,비김


CREATE TABLE COMMANT(
CKEY VARCHAR(100) PRIMARY KEY,
CONTENT TEXT(20000),
REF INT NOT NULL,
REFS INT NOT NULL,
LEV INT NOT NULL,
ID VARCHAR(100) NOT NULL,
PBOARD VARCHAR(100) NOT NULL,
FOREIGN KEY (ID) REFERENCES USER(ID)
);


